services:
  - type: web
    name: cachet
    env: docker
    plan: free
    buildCommand: "docker build -t cachet --build-arg cachet_ver=2.4 ."
    startCommand: "docker run -d --name cachet --link postgres -e DB_DRIVER=pgsql -e DB_HOST=S{DB_HOST} -e DB_PORT=${DB_PORT} -e DB_DATABASE=S{DB_DATABASE} -e DB_USERNAME=${DB_USERNAME} -e DB_PASSWORD=${DB_PASSWORD} -e DB_PREFIX=${DB_PREFIX} -d cachet"
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: postgres
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: postgres
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: postgres
          property: password
      - key: DB_PREFIX
        value: "chq_"
      - key: APP_KEY
        value: "${APP_KEY:-null}" # You might need to generate this key and manually set it in Render's environment variables
      - key: APP_LOG
        value: "errorlog"
      - key: APP_ENV
        value: "${APP_ENV:-production}"
      - key: APP_DEBUG
        value: "false"
      - key: DEBUG
        value: "false"

databases:
  - name: postgress
    databaseName: postgres
